backend:
  name: git-gateway
  branch: main
  repo: chorakchi/nextjs-netlify-blog-template
  site_domain: kaleidoscopic-lollipop-d26187.netlify.app",
  access_token: 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